# Generated by Django 3.2.13 on 2022-12-26 14:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsHistoryAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('is_auth', models.BooleanField(default=False)),
                ('expired_at', models.DateTimeField(default=datetime.datetime(2022, 12, 26, 14, 19, 13, 94811, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('encrypted_password', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SmsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_type', models.CharField(max_length=255)),
                ('send_to', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('is_succeed', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='odoq_models.smshistoryauth')),
            ],
        ),
    ]
