# Generated by Django 3.2.13 on 2022-12-26 14:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('odoq_models', '0002_alter_smshistoryauth_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smshistoryauth',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 26, 14, 34, 23, 275019, tzinfo=utc)),
        ),
    ]
