# Generated by Django 3.2.13 on 2023-03-26 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odoq_models', '0003_alter_smshistoryauth_expired_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('encrypted_password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=255)),
                ('img', models.ImageField(null=True, upload_to='')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('season', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='')),
                ('answer', models.CharField(max_length=255)),
                ('upload_datetime', models.DateTimeField(null=True)),
                ('answer_count', models.PositiveIntegerField(default=0)),
                ('solve_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='accept_sms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='smshistory',
            name='auth',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='odoq_models.smshistoryauth'),
        ),
        migrations.AlterField(
            model_name='smshistoryauth',
            name='expired_at',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blind', models.BooleanField(default=False)),
                ('blind_text', models.CharField(default='작성자에 의하여 블라인드 처리되었습니다.', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odoq_models.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnswerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('isSolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odoq_models.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odoq_models.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='answered_questions',
            field=models.ManyToManyField(blank=True, default=None, related_name='answered_users', to='odoq_models.Question'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_posts',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked_users', to='odoq_models.Post'),
        ),
        migrations.AddField(
            model_name='user',
            name='solved_questions',
            field=models.ManyToManyField(blank=True, default=None, related_name='solved_users', to='odoq_models.Question'),
        ),
    ]
