# Generated by Django 3.2.13 on 2023-04-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoq_models', '0005_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='제목 이전 포스트들입니다.', max_length=255),
        ),
    ]
