# Generated by Django 3.2.13 on 2023-04-30 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odoq_models', '0006_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='제목 만들어지기전 포스트들입니다.', max_length=255),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='odoq_models.post')),
                ('answer', models.CharField(max_length=255)),
                ('isSolved', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odoq_models.question')),
            ],
            bases=('odoq_models.post',),
        ),
    ]
