# Generated by Django 3.2.13 on 2023-05-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odoq_models', '0007_auto_20230501_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='read_count',
            new_name='hit_count',
        ),
    ]
