# Generated by Django 3.2.13 on 2023-05-07 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odoq_models', '0008_rename_read_count_post_hit_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('img', models.ImageField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blind', models.BooleanField(default=False)),
                ('blind_text', models.CharField(default='작성자에 의하여 블라인드 처리되었습니다.', max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odoq_models.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odoq_models.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cocomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blind', models.BooleanField(default=False)),
                ('blind_text', models.CharField(default='작성자에 의하여 블라인드 처리되었습니다.', max_length=100)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odoq_models.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odoq_models.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
