# Generated by Django 3.2.13 on 2023-05-14 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odoq_models', '0010_auto_20230507_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cocomment',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='season',
            new_name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(default='normal', max_length=255),
        ),
        migrations.AlterField(
            model_name='cocomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocomments', to='odoq_models.comment'),
        ),
    ]
