# Generated by Django 3.2.13 on 2023-05-21 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odoq_models', '0011_auto_20230515_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='comment',
            name='notice',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='odoq_models.notice'),
        ),
        migrations.AddField(
            model_name='notice',
            name='hit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notice',
            name='is_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notice',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='odoq_models.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='like_notices',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked_users', to='odoq_models.Notice'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='odoq_models.post'),
        ),
    ]
