# Generated by Django 3.2.13 on 2023-05-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoq_models', '0012_auto_20230521_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cheated_questions',
            field=models.ManyToManyField(blank=True, default=None, related_name='cheated_users', to='odoq_models.Question'),
        ),
    ]
