# Generated by Django 3.2.13 on 2023-05-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoq_models', '0013_user_cheated_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='notice',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
