# Generated by Django 3.2.13 on 2023-06-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoq_models', '0015_alter_notice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerhistory',
            name='over_limit',
            field=models.BooleanField(default=False),
        ),
    ]
