upstream django {
    server 127.0.0.1:8000;
}

server {
    listen 80;
    server_name api.odoq2.com;
    charset utf-8;
    if ($http_x_forwarded_proto = 'http') {
        return 301 https://$host$request_uri;
    }
    client_max_body_size 75M;

    # STATIC FILES
    location /static {
        alias /home/ubuntu/odoq_back_second/static;
    }

    # MEDIA FILES
    location /media {
        alias /home/ubuntu/odoq_back_second/media;
    }

    # API
    location / {
        uwsgi_pass django;
        include /home/ubuntu/odoq_back_second/uwsgi_params;
    }
}